baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Erik Aouizerate"

metaDataFormat = "toml"

[[menu.main]]
    name = "ABOUT"
    url = "#about"
    weight = 10
[[menu.main]]
    name = "PROJECTS"
    url = "#projects"
    weight = 20
[[menu.main]]
    name = "EXPERIENCES"
    url = "#experiences"
    weight = 30
[[menu.main]]
    name = "CONTACT"
    url = "#contact"
    weight = 40