baseurl = "http://mejjjor.github.io/erik-web"
canonifyurls = true
disableRSS=true
metaDataFormat = "toml"

languageCode = "en-us"
title = "Erik Aouizerate - développeur informatique full stack"

contentdir = "content/fr"


[params]
    locale = "fr-FR"
    description = "Page personnelle d'Erik Aouizerate - compétences et projets réalisés"
    generator="Hugo 0.14"
    author = "Erik Aouizerate"
    subdomain = "erik-web"

[[menu.main]]
    name = "A PROPOS"
    url = "about"
    weight = 10
[[menu.main]]
    name = "PROJETS"
    url = "projects"
    weight = 20
[[menu.main]]
    name = "EXPERIENCES"
    url = "experiences"
    weight = 30
[[menu.main]]
    name = "CONTACT"
    url = "contact"
    weight = 40