baseurl = "http://mejjjor.github.io/erik-web"
languageCode = "en-us"
title = "Erik Aouizerate - full stack developer"

publishdir = "public/en"

metaDataFormat = "toml"

contentdir = "content/en"
[params]
    locale = "en-US"
    description = "Erik Aouizerate's personal web site - skills and projects description"
    generator="Hugo 0.14"
    author = "Erik Aouizerate"

[[menu.main]]
    name = "ABOUT"
    url = "about"
    weight = 10
[[menu.main]]
    name = "PROJECTS"
    url = "projects"
    weight = 20
[[menu.main]]
    name = "EXPERIENCES"
    url = "experiences"
    weight = 30
[[menu.main]]
    name = "CONTACT"
    url = "contact"
    weight = 40